# Generated by Django 5.2.9 on 2026-01-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pin_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
